require("settings")
require("keymaps")
require("plugins")
require("colorscheme")
require("lsp")

-- Plugin configurations
require("config.nvimtree")
require("config.telescope")
require("config.mason")
require("config.lualine")
require("config.treesitter")
require("config.cmp")
require("config.gitsigns")
require("config.harpoon")
require("config.null-ls")
require("config.dap")
require("config.whichkey")
require("config.alpha")
require("config.bloodmoon")
require("config.bloodgates")
require("config.bloodstorm")
require("config.bloodrain")
